const MS_SECOND = 1000;
const MS_MINUTE = MS_SECOND * 60;
const MS_HOUR = MS_MINUTE * 60;
const MS_DAY = MS_HOUR * 24;
const MS_MONTH = MS_DAY * 30;

export const TIME = {
  SECOND: MS_SECOND,
  MINUTE: MS_MINUTE,
  HOUR: MS_HOUR,
  DAY: MS_DAY,
  MONTH: MS_MONTH,
};
